name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Print Flutter version
        run: flutter --version

      - name: Create Flutter project
        run: |
          flutter create flutter_so
          cd flutter_so
          flutter pub get

      - name: Build APK for arm64 and armeabi-v7a
        run: |
          cd flutter_so
          flutter build apk --release --target-platform android-arm,android-arm64

      - name: Find libflutter.so files
        id: find_so
        run: |
          cd flutter_so/build
          find . -type f -name "libflutter.so" > files.txt
          echo "found_files=$(cat files.txt | tr '\n' ';')" >> $GITHUB_OUTPUT

      - name: Upload libflutter.so files
        uses: actions/upload-artifact@v4
        with:
          name: flutter_so_libs
          path: ${{ steps.find_so.outputs.found_files }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: flutter_so/build/app/outputs/flutter-apk/app-release.apk
